version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: sistema_alunos_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: sistema_alunos
    ports:
      - "5545:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: